// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuGO0gJ5ILMA1pu4PLmVW8nt_0vjo4xvo',
    appId: '1:985352351105:web:fddd7eeed58e561941cc80',
    messagingSenderId: '985352351105',
    projectId: 'geze-om',
    authDomain: 'geze-om.firebaseapp.com',
    storageBucket: 'geze-om.appspot.com',
    measurementId: 'G-R3693BDBDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbF4eomQkox2Z3wZCJCrdIFyUOEqk4iCg',
    appId: '1:985352351105:android:936ba2be01e2dd6b41cc80',
    messagingSenderId: '985352351105',
    projectId: 'geze-om',
    storageBucket: 'geze-om.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMtOGYpOFaqjeY-M7iLcP2ULms89sCgLY',
    appId: '1:985352351105:ios:d8b09ea11692e06e41cc80',
    messagingSenderId: '985352351105',
    projectId: 'geze-om',
    storageBucket: 'geze-om.appspot.com',
    iosClientId: '985352351105-2hb02ppfc9ltka1uuu0u040lb0gfu7nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.userGeze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMtOGYpOFaqjeY-M7iLcP2ULms89sCgLY',
    appId: '1:985352351105:ios:d8b09ea11692e06e41cc80',
    messagingSenderId: '985352351105',
    projectId: 'geze-om',
    storageBucket: 'geze-om.appspot.com',
    iosClientId: '985352351105-2hb02ppfc9ltka1uuu0u040lb0gfu7nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.userGeze',
  );
}
